apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: 110588987466.dkr.ecr.us-east-1.amazonaws.com/shopping-site-books:710004d8b2448339408a85c3cd31dd85d8af9d34
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
